server.port=8085

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/analyticsdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=n@dhirah10594
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Circuit Breaker Configurations (Resilience4j)
resilience4j.circuitbreaker.instances.downstreamServices.failureRateThreshold=50
resilience4j.circuitbreaker.instances.downstreamServices.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.downstreamServices.slidingWindowSize=10
